import React, { useState, useEffect } from 'react';
import { Send, CheckCircle2, Terminal, AlertCircle } from 'lucide-react';
import { AutomationResult } from '../types';

interface ContactSectionProps {
  id?: string;
  automationContext?: AutomationResult | null;
}

const ContactSection: React.FC<ContactSectionProps> = ({ id, automationContext }) => {
  const [formState, setFormState] = useState({
    name: '',
    email: '',
    message: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Auto-fill message if context exists
  useEffect(() => {
    if (automationContext) {
      const strategyText = `I would like to implement the following automation strategy generated by Raynaters AI:

STRATEGY:
${automationContext.strategy}

PROJECTED ROI:
${automationContext.marketData?.[4]?.value || 'High'} hours saved/month efficiency gain.

Can we discuss the implementation steps?`;

      setFormState(prev => ({
        ...prev,
        message: strategyText
      }));
    }
  }, [automationContext]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      // Using FormSubmit.co AJAX to send email without backend
      const response = await fetch("https://formsubmit.co/ajax/shahzarrayyan123@gmail.com", {
        method: "POST",
        headers: { 
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        },
        body: JSON.stringify({
            name: formState.name,
            email: formState.email,
            message: formState.message,
            _subject: `New Lead: ${formState.name} - Raynaters`,
            _template: "table"
        })
      });

      const result = await response.json();

      if (response.ok) {
        setIsSubmitted(true);
        setFormState({ name: '', email: '', message: '' });
      } else {
        setError("Something went wrong. Please try again or email us directly.");
        console.error("Form submission failed:", result);
      }
    } catch (err) {
      setError("Network error. Please check your connection.");
      console.error("Form submission error:", err);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <section id={id} className="py-24 bg-slate-50 relative overflow-hidden">
      {/* Background Circuitry */}
      <div className="absolute inset-0 opacity-5 pointer-events-none">
         <div className="absolute top-1/4 left-10 w-64 h-64 border border-[#0551a2] rounded-full animate-[spin_10s_linear_infinite]"></div>
         <div className="absolute bottom-1/4 right-10 w-96 h-96 border border-blue-400 rounded-full animate-[spin_15s_linear_infinite_reverse]"></div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-24 items-center">
          
          {/* Left Side: AI Visuals & Info */}
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white border border-slate-200 text-[#0551a2] text-xs font-semibold mb-6 shadow-sm">
              <span className="w-2 h-2 rounded-full bg-[#0551a2] animate-pulse"></span>
              24/7 AI Reception
            </div>
            <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6 leading-tight tracking-tight">
              Ready to <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#0551a2] to-blue-600">Automate</span> Your Future?
            </h2>
            <p className="text-slate-600 text-lg mb-8 leading-relaxed font-light">
              Whether you need a full audit or a specific agent, our team is ready to deploy. Drop your details, and our AI will route your request to the perfect specialist.
            </p>

            <div className="bg-white border border-slate-200/60 rounded-2xl p-6 relative overflow-hidden shadow-sm">
               <div className="flex items-center gap-2 mb-4 border-b border-slate-100 pb-2">
                 <Terminal size={16} className="text-[#0551a2]" />
                 <span className="text-xs font-mono text-slate-400">SYSTEM_LOG</span>
               </div>
               <div className="space-y-3 font-mono text-sm">
                 <div className="flex items-center gap-2 text-slate-500">
                   <span className="text-[#0551a2]">➜</span>
                   <span>Initializing contact protocol...</span>
                 </div>
                 {automationContext ? (
                    <div className="flex items-start gap-2 text-green-600 animate-pulse">
                      <span className="text-green-500 mt-1">➜</span>
                      <span>
                        Context Loaded: Strategy Audit<br/>
                        <span className="text-xs opacity-70 text-slate-500">Auto-filled into message box.</span>
                      </span>
                    </div>
                 ) : (
                    <div className="flex items-center gap-2 text-slate-400">
                      <span className="text-slate-500">➜</span>
                      <span>Waiting for user input...</span>
                    </div>
                 )}
                 <div className="flex items-center gap-2 text-slate-400">
                    <span className="text-slate-500">➜</span>
                    <span className="animate-[blink_1s_step-end_infinite]">_</span>
                 </div>
               </div>
            </div>
          </div>

          {/* Right Side: Form */}
          <div className="relative">
            <div className="absolute -inset-1 bg-gradient-to-r from-slate-200 via-blue-50 to-slate-200 rounded-3xl blur opacity-40"></div>
            <div className="relative bg-white border border-slate-100 rounded-2xl p-8 shadow-2xl shadow-slate-200/50">
              
              {isSubmitted ? (
                <div className="text-center py-12 animate-[fadeIn_0.5s_ease-out]">
                   <div className="w-20 h-20 bg-green-50 rounded-full flex items-center justify-center mx-auto mb-6 text-green-600">
                     <CheckCircle2 size={40} />
                   </div>
                   <h3 className="text-2xl font-bold text-slate-900 mb-2">Transmission Received</h3>
                   <p className="text-slate-500 mb-6">Our agents are processing your request. We have sent a confirmation to your email.</p>
                   <button 
                    onClick={() => setIsSubmitted(false)}
                    className="mt-4 text-[#0551a2] hover:text-blue-800 text-sm font-medium border-b border-transparent hover:border-[#0551a2] transition-colors"
                   >
                     Send another message
                   </button>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-6">
                  <div>
                    <h3 className="text-2xl font-bold text-slate-900 mb-1">Get in Touch</h3>
                    <p className="text-slate-500 text-sm">Fill out the form below or book a call directly.</p>
                  </div>

                  <div className="space-y-4">
                    <div>
                      <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Full Name</label>
                      <input 
                        type="text"
                        name="name"
                        required
                        value={formState.name}
                        onChange={(e) => setFormState({...formState, name: e.target.value})}
                        className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-900 focus:outline-none focus:border-[#0551a2] focus:ring-1 focus:ring-[#0551a2] transition-all placeholder-slate-400"
                        placeholder="John Doe"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Email Address</label>
                      <input 
                        type="email"
                        name="email"
                        required
                        value={formState.email}
                        onChange={(e) => setFormState({...formState, email: e.target.value})}
                        className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-900 focus:outline-none focus:border-[#0551a2] focus:ring-1 focus:ring-[#0551a2] transition-all placeholder-slate-400"
                        placeholder="john@company.com"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
                        How can we help?
                        {automationContext && <span className="ml-2 text-[#0551a2] text-[10px] normal-case bg-blue-50 px-2 py-0.5 rounded-full border border-blue-200 flex-inline items-center gap-1 animate-pulse">Strategy Attached</span>}
                      </label>
                      <textarea 
                        name="message"
                        required
                        value={formState.message}
                        onChange={(e) => setFormState({...formState, message: e.target.value})}
                        className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-slate-900 focus:outline-none focus:border-[#0551a2] focus:ring-1 focus:ring-[#0551a2] transition-all min-h-[160px] resize-none placeholder-slate-400 font-sans"
                        placeholder="Tell us about your automation needs..."
                      />
                    </div>
                  </div>

                  {error && (
                    <div className="flex items-center gap-2 text-red-500 text-sm bg-red-50 p-3 rounded-lg border border-red-100">
                      <AlertCircle size={16} /> {error}
                    </div>
                  )}

                  <button 
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-[#0551a2] text-white font-bold py-4 rounded-xl hover:bg-blue-800 transition-colors flex items-center justify-center gap-2 shadow-lg shadow-blue-900/10 disabled:opacity-70 disabled:cursor-not-allowed"
                  >
                    {isSubmitting ? (
                      <span className="animate-pulse flex items-center gap-2">Sending Transmission...</span>
                    ) : (
                      <>
                        Send Message <Send size={18} />
                      </>
                    )}
                  </button>
                  
                  <p className="text-center text-[10px] text-slate-400">
                    By submitting, you agree to receive communications from Raynaters Agency.
                  </p>
                </form>
              )}
            </div>
          </div>

        </div>
      </div>
    </section>
  );
};

export default ContactSection;